# Generated by Django 5.1.3 on 2025-04-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_negative',
            field=models.BooleanField(default=False),
        ),
    ]
