# Generated by Django 5.1.3 on 2025-04-13 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_notification_is_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
    ]
