# Generated by Django 5.1.3 on 2025-04-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='diagram_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='export',
            field=models.BooleanField(default=False, help_text='Indicates if users can export diagram'),
        ),
        migrations.AddField(
            model_name='plan',
            name='live_sync',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='table_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='team_collaboration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='version_control',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='monthly_price',
            field=models.IntegerField(default=0),
        ),
    ]
