# Generated by Django 5.1.3 on 2025-04-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='amount_paid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
