# Generated by Django 5.1.3 on 2025-04-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_plan_popular_subscription_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='style_id',
            field=models.IntegerField(default=1),
        ),
    ]
