# Generated by Django 5.1.3 on 2025-04-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_plan_style_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='features',
        ),
        migrations.AddField(
            model_name='plan',
            name='features',
            field=models.TextField(default='First,', help_text='Comma separated list of features'),
            preserve_default=False,
        ),
    ]
