# Generated by Django 5.1.3 on 2025-04-11 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_remove_plan_features_plan_features'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['monthly_price']},
        ),
    ]
