# Generated by Django 5.1.3 on 2025-04-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_alter_plan_currency_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='paystack_yearly_plan_code',
            field=models.TextField(blank=True, help_text='Plan code of the yearly plan on paystack', null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='paystack_plan_code',
            field=models.TextField(blank=True, help_text='Plan code of the monthly plan on paystack', null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='duration',
            field=models.IntegerField(help_text='duration in months'),
        ),
    ]
