# Generated by Django 5.1.3 on 2025-04-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('subscription', 'Subscription'), ('diagram_charge', 'Diagram charge')], default='diagram_charge', max_length=25),
        ),
    ]
