# Generated by Django 5.1.3 on 2025-04-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payload',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
