# Generated by Django 5.1.3 on 2025-04-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_transaction_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='customer_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
