# Generated by Django 5.1.3 on 2025-09-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_subscription_customer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='stripe_monthly_plan_id',
            field=models.TextField(blank=True, help_text='Plan id of the monthly plan on stripe', null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='stripe_yearly_plan_id',
            field=models.TextField(blank=True, help_text='Plan id of the yearly plan on stripe', null=True),
        ),
    ]
