# Generated by Django 5.1.3 on 2025-09-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_plan_stripe_monthly_plan_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment_gateway',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('stripe', 'Stripe')], default='paystack'),
        ),
    ]
