# Generated by Django 5.1.3 on 2024-12-22 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagram',
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='DatabaseTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('x_position', models.FloatField()),
                ('y_position', models.FloatField()),
                ('description', models.TextField()),
                ('diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagram.diagram')),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('datatype', models.CharField(max_length=50)),
                ('is_primary_key', models.BooleanField(default=False)),
                ('is_nullable', models.BooleanField(default=False)),
                ('is_unique', models.BooleanField(default=False)),
                ('comment', models.TextField()),
                ('default_value', models.CharField(max_length=255)),
                ('db_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagram.databasetable')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_column_rels', to='diagram.databasecolumn')),
                ('to_column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_column_rels', to='diagram.databasecolumn')),
            ],
        ),
    ]
