# Generated by Django 5.1.3 on 2024-12-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0002_alter_diagram_options_databasetable_databasecolumn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databasetable',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
