# Generated by Django 5.1.3 on 2025-01-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0003_alter_databasetable_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasecolumn',
            name='synced',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='databasetable',
            name='synced',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='diagram',
            name='synced',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='relationship',
            name='synced',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='databasecolumn',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='databasetable',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
