# Generated by Django 5.1.3 on 2025-01-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0004_databasecolumn_synced_databasetable_synced_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasetable',
            name='flow_id',
            field=models.IntegerField(default=-1),
        ),
    ]
