# Generated by Django 5.1.3 on 2025-01-21 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0005_databasetable_flow_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='diagram',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='diagram.diagram'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='databasecolumn',
            name='default_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
