# Generated by Django 5.1.3 on 2025-01-24 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0006_relationship_diagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='source_suffix',
            field=models.CharField(default='ls', max_length=10),
        ),
        migrations.AddField(
            model_name='relationship',
            name='target_suffix',
            field=models.CharField(default='rt', max_length=10),
        ),
    ]
