# Generated by Django 5.1.3 on 2025-01-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0007_relationship_source_suffix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='from_rel',
            field=models.CharField(choices=[('one', 'One'), ('many', 'Many')], default='one', max_length=6),
        ),
        migrations.AddField(
            model_name='relationship',
            name='to_rel',
            field=models.CharField(choices=[('one', 'One'), ('many', 'Many')], default='one', max_length=6),
        ),
    ]
