# Generated by Django 5.1.3 on 2025-01-30 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0009_alter_diagram_database_type_diagrammember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='diagram',
            name='writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagramwrites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='diagram',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagrams', to=settings.AUTH_USER_MODEL),
        ),
    ]
