# Generated by Django 5.1.3 on 2025-04-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0010_diagram_writer_alter_diagram_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagram',
            name='live_sync',
            field=models.BooleanField(default=False),
        ),
    ]
