# Generated by Django 5.1.3 on 2025-04-07 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0011_diagram_live_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasecolumn',
            name='flow_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
