# Generated by Django 5.1.3 on 2025-04-11 04:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0012_databasecolumn_flow_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='databasecolumn',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='databasecolumn',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='databasecolumn',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
