# Generated by Django 5.1.3 on 2025-04-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0014_diagram_amount_paid_diagram_pay_per_diagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagram',
            name='has_paid',
            field=models.BooleanField(default=True),
        ),
    ]
