# Generated by Django 5.1.3 on 2025-04-14 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0015_diagram_has_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagramInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagram.diagram')),
            ],
        ),
    ]
