# Generated by Django 5.1.3 on 2025-04-14 11:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0016_diagraminvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagraminvitation',
            name='expiry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
