# Generated by Django 5.1.3 on 2025-04-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0017_diagraminvitation_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagraminvitation',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
