# Generated by Django 5.1.3 on 2025-04-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0018_diagraminvitation_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagraminvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending'),
        ),
    ]
