# Generated by Django 5.1.3 on 2025-04-17 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0019_diagraminvitation_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='databasecolumn',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='databasetable',
            options={'ordering': ['-created_at']},
        ),
    ]
