# Generated by Django 5.1.3 on 2025-09-28 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0020_alter_databasecolumn_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databasetable',
            name='diagram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='diagram.diagram'),
        ),
    ]
