# Generated by Django 5.1.3 on 2025-09-28 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0021_alter_databasetable_diagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databasecolumn',
            name='db_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='diagram.databasetable'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='diagram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='diagram.diagram'),
        ),
    ]
