# Generated by Django 5.1.3 on 2025-10-15 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0022_alter_databasecolumn_db_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportedExportFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fe_image_url', models.CharField(max_length=255)),
                ('extension', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
