# Generated by Django 5.1.3 on 2025-10-15 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0023_supportedexportformat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupportedExportFormat',
        ),
    ]
